POST http://localhost:3001/api/blogs
Content-Type: application/json


{
  //"title": "Full Stack devaus ei ole helppoa",
  "author": "Julle Juniori",
  "url": "http://localhost:3001/api/blogs",
  "likes": ""
}

