POST http://localhost:3001/api/blogs
Content-Type: application/json


{
  "title": "MyDay",
  "author": "Erkki Esimerkki",
  "url": "http://localhost:3001/api/blogs",
  "likes": 14,
  "userId": "65412eaff095dfb04a091a64"
}

